### ISSUE TITLE
Error Could not pass event BlockBreakEvent to AntiCheatPlus v2.1.4

### ISSUE THREAD

**Issue by ghost** [m1enkrafftman/AntiCheatPlus#13]
I get this error:
]: Could not pass event BlockBreakEvent to AntiCheatPlus v2.1.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:637) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at net.dynamicdev.anticheat.util.BlockHardness.getHardness(BlockHardness.java:215) ~[?:?]
        at net.dynamicdev.anticheat.util.BlockHardness.getBlockHardness(BlockHardness.java:205) ~[?:?]
        at net.dynamicdev.anticheat.util.Utilities.calcSurvivalFastBreak(Utilities.java:579) ~[?:?]
        at net.dynamicdev.anticheat.check.checks.BlockCheck.checkFastBreak(BlockCheck.java:116) ~[?:?]
        at net.dynamicdev.anticheat.event.BlockListener.onBlockBreak(BlockListener.java:79) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        ... 17 more

**Comment by DarkWav** [comment]
Don´t worry!
Its just a problem of Spigot.
If you use Bukkit it will work this error won´t be spammed in your console.

**Comment by ghost** [comment]
spigot is a fork of bukkit - that is not the error. Are you sure you have a compatible version?

**Comment by darkspirit510** [comment]
As DarkWav said, after we switched from Bukkit to Spigot, we now get some similar errors, but with different events:

[12:07:38] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to AntiCheatPlus v2.1.4
[...]
Caused by: java.lang.NullPointerException
    at net.dynamicdev.anticheat.check.checks.MovementCheck.checkWaterWalk(MovementCheck.java:424) ~[?:?]
    at net.dynamicdev.anticheat.event.PlayerListener.onPlayerMove(PlayerListener.java:431) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor1267.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]

Is this plugin still in development?
